import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Loading from '../layout/globalComponents/Loading'
import NavBar from '../layout/globalComponents/NavBar'
import HomeScreen from '../layout/HomeScreen'

export default function Home() {
  const [loadingState, setLoadingState] = useState(true)
  const router = useRouter()

  useEffect(() => {
    setTimeout(() => {
      if (!localStorage.getItem('pos-system-token')) {
        router.push('/login')
      } else {
        setLoadingState(false)
      }
    }, 1000)
  }, [])

  return (
    <>
      <Head>
        <title>POS - System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loading LoadingState={loadingState} />
      <NavBar />
      <HomeScreen />
    </>
  )
}
